name: Despliegue en GitHub Pages

on:
  # El workflow se ejecutarÃ¡ cuando haya un push a la rama 'main'
  push:
    branches:
      - main
  
  # TambiÃ©n permite ejecutar el workflow manualmente desde la interfaz de GitHub
  workflow_dispatch:

# Permite que el workflow pueda interactuar con GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Define un Ãºnico trabajo llamado 'deploy'
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio ğŸ›ï¸
        # Baja el cÃ³digo del repositorio
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages âš™ï¸
        # Configura el ambiente de GitHub Pages
        uses: actions/configure-pages@v4

      - name: Subir artefacto (Tus archivos web) ğŸ“¦
        # Sube todos los archivos de la raÃ­z del proyecto
        uses: actions/upload-pages-artifact@v3
        with:
          # Indicamos que suba todo lo que estÃ¡ en la raÃ­z del proyecto
          path: './'

      - name: Despliegue a GitHub Pages ğŸš€
        id: deployment
        # Ejecuta el despliegue final
        uses: actions/deploy-pages@v4